FROM nginx:alpine

# Copia todos os arquivos da raiz (HTML, JS, etc) para a pasta do Nginx
COPY . /usr/share/nginx/html

# Garante que o mock-gas.js esteja presente e remove arquivos desnecessários
RUN rm -rf /usr/share/nginx/html/backend \
    && rm -rf /usr/share/nginx/html/.clasp.json \
    && rm -rf /usr/share/nginx/html/appsscript.json \
    && rm -rf /usr/share/nginx/html/.git

EXPOSE 80
