version: "3.7"

services:
  oda-backend:
    image: oda-backend:latest
    networks:
      - dockermaster
    environment:
      - GEMINI_API_KEY="AIzaSyDOfwLJx3035-JswcuI1YY-pxOsqaO4gwA"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.oda-backend.rule=Host(`api.lab.inetz.com.br`)"
        - "traefik.http.routers.oda-backend.entrypoints=websecure"
        - "traefik.http.routers.oda-backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.oda-backend.tls=true"
        - "traefik.http.routers.oda-backend-http.rule=Host(`api.lab.inetz.com.br`)"
        - "traefik.http.routers.oda-backend-http.entrypoints=web"
        - "traefik.http.services.oda-backend.loadbalancer.server.port=5000"
        - "traefik.docker.network=dockermaster"

  oda-frontend:
    image: nginx:alpine
    networks:
      - dockermaster
    volumes:
      - /var/inetpub/wwwroot/oda:/usr/share/nginx/html:ro
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.oda-frontend.rule=Host(`lab.inetz.com.br`)"
        - "traefik.http.routers.oda-frontend.entrypoints=websecure"
        - "traefik.http.routers.oda-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.oda-frontend.tls=true"
        - "traefik.http.routers.oda-frontend-http.rule=Host(`lab.inetz.com.br`)"
        - "traefik.http.routers.oda-frontend-http.entrypoints=web"
        - "traefik.http.services.oda-frontend.loadbalancer.server.port=80"
        - "traefik.docker.network=dockermaster"

networks:
  dockermaster:
    external: true
